name: Continous integration

on:
  pull_request:
  push:
    branches:
      - develop
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.6"
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox
        run: pip install tox
      - name: Lint
        run: tox -e lint

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install miniwdl-slurm
        run: pip install .
      - name: install ansible
        run: sudo apt-get install ansible
      - name: download slurm and singularity roles
        run: sudo ansible-galaxy install galaxyproject.slurm cyverse-ansible.singularity
      - name: install slurm and singularity on this node
        run: sudo ansible-playbook tests/slurm_playbook.yml -vv
      - name: Check slurm logs
        run: "sudo bash -c 'cat /var/log/slurm/*'"
      - name: run miniwdl self test
        run: miniwdl run-self-test --cfg tests/miniwdl.cfg
